name: Login Load Test
on:
  workflow_dispatch:

jobs:
  k6-login-test:
    name: Run k6 Login Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run k6 load test
        uses: grafana/k6-action@v0.3.1
        with:
          # Đảm bảo đường dẫn này chính xác
          filename: load-testing/test.js
        env:
          # Lấy URL mục tiêu từ GitHub Secrets và truyền vào kịch bản k6
          TARGET_URL: ${{ secrets.TARGET_URL }}
