name: certapple

on:
  workflow_dispatch:

jobs:
  certapple-run:
    name: Run certapple Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run certapple test
        # Sử dụng phiên bản mới nhất của k6-action
        uses: grafana/k6-action@v0.3.1
        # Cung cấp tham số đầu vào cho Action
        with:
          filename: load-testing/test.js
        # Đặt biến môi trường cho bước này. Đây là cách làm đúng.
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
