name: k6 Debug Workflow

on:
  # Cho phép chạy thủ công từ tab Actions trên GitHub
  workflow_dispatch:

jobs:
  k6-debug-test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Lấy mã nguồn từ repository của bạn
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Cài đặt k6 lên máy ảo runner
      # Máy ảo của GitHub không có sẵn k6, nên chúng ta cần cài nó.
      - name: Install k6
        run: |
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6

      # Step 3: Chạy k6 và lưu lại toàn bộ log
      # Bước này chỉ dùng 'run' để thực thi lệnh shell.
      - name: Run k6 and capture debug log
        # continue-on-error: true sẽ đảm bảo bước upload log vẫn chạy
        # ngay cả khi k6 báo lỗi (test failed).
        continue-on-error: true
        run: |
          # Lệnh này chạy k6 với chế độ debug và lưu tất cả output (cả lỗi)
          # vào file k6-debug-output.log
          k6 run --vus 1 --iterations 1 --http-debug="full" certapple_test.js > k6-debug-output.log 2>&1
          
      # Step 4: Upload file log đã tạo thành một "artifact"
      # Artifact là file được lưu lại sau khi workflow chạy xong để bạn tải về.
      - name: Upload k6 debug log
        uses: actions/upload-artifact@v3
        with:
          name: k6-debug-log
          path: k6-debug-output.log
