# File: .github/workflows/performance-test.yml (PHIÊN BẢN SỬA LỖI CUỐI CÙNG)

name: Website Performance Test

on:
  workflow_dispatch:
    inputs:
      virtual_users:
        description: 'Tổng số người dùng ảo (VUs)'
        required: true
        default: '50'
      duration:
        description: 'Thời gian test (ví dụ: 2m, 5m)'
        required: true
        default: '2m'

jobs:
  k6-performance-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Run k6 test
        uses: grafana/k6-action@v0.3.1
        with:
          # Đường dẫn đến file kịch bản
          filename: tests/website-flow.js

          # --- THAY ĐỔI QUAN TRỌNG NHẤT NẰM Ở ĐÂY ---
          # Sử dụng `flags` để truyền trực tiếp các tham số dòng lệnh cho k6
          # Điều này sẽ ghi đè lên các giá trị trong khối `options` của script.
          flags: --vus ${{ github.event.inputs.virtual_users }} --duration ${{ github.event.inputs.duration }}

        env:
          # Chúng ta vẫn cần `env` để truyền TARGET_URL, vì nó không phải là một flag tiêu chuẩn của k6
          TARGET_URL: 'https://cert.khoindvn.io.vn'
