# File: .github/workflows/performance-test.yml (PHIÊN BẢN CHUẨN)

name: Website Performance Test

on:
  workflow_dispatch:
    inputs:
      virtual_users:
        description: 'Tổng số người dùng ảo (VUs)'
        required: true
        default: '50'
      duration:
        description: 'Thời gian test (ví dụ: 2m, 5m)'
        required: true
        default: '2m'

jobs:
  k6-performance-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Run k6 test
        uses: grafana/k6-action@v0.3.1
        with:
          # Chỉ định file kịch bản
          filename: tests/website-flow.js
        env:
          # --- QUAY TRỞ LẠI DÙNG `env` ĐỂ TRUYỀN TẤT CẢ CÁC GIÁ TRỊ ---
          TARGET_URL: 'https://cert.khoindvn.io.vn'
          VUS: ${{ github.event.inputs.virtual_users }}
          DURATION: ${{ github.event.inputs.duration }}
