# File: .github/workflows/performance-test.yml

name: Website Performance Test

# --- KHI NÀO WORKFLOW NÀY SẼ CHẠY ---
on:
  # Cho phép bạn chạy thủ công từ tab Actions trên GitHub
  workflow_dispatch:
    inputs:
      # Form nhập liệu sẽ hiện ra khi bạn nhấn "Run workflow"
      virtual_users:
        description: 'Tổng số người dùng ảo (VUs)'
        required: true
        default: '2000' # Giá trị mặc định là 50
      duration:
        description: 'Thời gian test (ví dụ: 1m, 2m, 5m)'
        required: true
        default: '2000m' # Giá trị mặc định là 2 phút

# --- CÁC CÔNG VIỆC CẦN LÀM ---
jobs:
  k6-performance-test:
    runs-on: ubuntu-latest # Chạy trên một máy ảo Ubuntu mới nhất của GitHub
    timeout-minutes: 600    # Job sẽ tự hủy nếu chạy quá 15 phút

    steps: # Các bước tuần tự
      # Bước 1: Lấy mã nguồn từ repository của bạn về máy ảo
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Chạy k6 bằng Action chính thức của Grafana k6
      - name: 2. Run k6 test
        uses: grafana/k6-action@v0.3.1
        with:
          # Chỉ định file kịch bản cần chạy
          filename: tests/website-flow.js
        env:
          # --- PHẦN KẾT NỐI QUAN TRỌNG NHẤT ---
          # Truyền các giá trị vào kịch bản k6 thông qua biến môi trường
          TARGET_URL: 'https://cert.khoindvn.io.vn' # URL của bạn được đặt cố định ở đây
          VUS: ${{ github.event.inputs.virtual_users }}   # Lấy giá trị từ form nhập liệu
          DURATION: ${{ github.event.inputs.duration }} # Lấy giá trị từ form nhập liệu
