name: Security Scan with OWASP ZAP

on:
  workflow_dispatch:

jobs:
  zap_scan:
    name: Run ZAP Baseline Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # *** BƯỚC SỬA LỖI QUAN TRỌNG ***
      # Thêm bước này để cấp quyền ghi cho thư mục làm việc.
      # Điều này sẽ giải quyết lỗi "Permission denied".
      - name: Grant Write Permissions to Workspace
        run: chmod -R 777 .

      # Bước chạy ZAP đã được cập nhật
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'https://certapple.com'

          # *** SỬA LỖI THAM SỐ ***
          # Đổi 'report_name' thành 'artifact_name' và xóa 'report_title'.
          # Tên này sẽ được dùng cho file zip chứa các báo cáo.
          artifact_name: 'zap-scan-reports'
          
          # Giữ nguyên tùy chọn này để workflow không bị lỗi đỏ nếu chỉ có cảnh báo.
          fail_action: false
