name: 'Kiểm tra Bảo mật (DoS/Payload Lớn)'
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  run-dos-test:
    name: 'Chạy Script Tấn công Payload Lớn'
    runs-on: ubuntu-latest
    steps:
      - name: '1. Tải mã nguồn về'
        uses: actions/checkout@v4
      - name: '2. Cài đặt Node.js (phiên bản 20.x)'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: '3. Cài đặt các dependencies (bao gồm Playwright)'
        run: npm install
      - name: '4. Cài đặt trình duyệt cho Playwright'
        run: npx playwright install --with-deps
      - name: '5. Chạy script kiểm tra tấn công'
        run: node attack_script_dos_test.js
# ghj hikk fuj fghj
    
