# .github/workflows/security-audit.yml

name: Kiểm Tra Bảo Mật Nâng Cao (Sử dụng Headless Browser)

on:
  workflow_dispatch:

jobs:
  advanced-security-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Lấy mã nguồn từ repository
        uses: actions/checkout@v3

      - name: Cài đặt Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # --- BƯỚC QUAN TRỌNG ĐƯỢC THÊM VÀO ---
      - name: Cài đặt các thư viện Node.js từ package.json
        run: npm install
      # ------------------------------------

      - name: Tải về các trình duyệt cho Playwright
        run: npx playwright install --with-deps

      - name: Chạy Script Tấn Công Brute-Force Nâng Cao
        run: node attack_script.js
