# ✅ File: .github/workflows/SlowContro2.yml
# WORKFLOW ĐIỀU KHIỂN VÒNG LẶP CUỐN CHIẾU (ROLLING UPDATE) - ĐÃ SỬA LỖI

name: '🔄 Điều Khiển Vòng Lặp Slow (Cuốn Chiếu)'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      target_url_1:
        description: 'URL mục tiêu chính (bắt buộc)'
        required: true
        default: 'https://certapple.com'
      target_url_2:
        description: 'URL mục tiêu thứ hai (tùy chọn, bỏ trống để chỉ dùng URL 1)'
        required: false
        default: ''
      wait_minutes:
        description: 'Số phút chờ giữa mỗi lần cập nhật cuốn chiếu'
        required: true
        default: '6'
      child_runs:
        description: 'Tổng số lần chạy con (worker) được duy trì'
        required: true
        default: '10' # Nên là số chẵn để chia 50% dễ dàng

jobs:
  loop_controller:
    name: 🔄 Vòng Lặp Điều Khiển Cuốn Chiếu
    runs-on: ubuntu-latest
    timeout-minutes: 350
    permissions:
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bắt đầu vòng lặp
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_URL_1: ${{ github.event.inputs.target_url_1 }}
          TARGET_URL_2: ${{ github.event.inputs.target_url_2 }}
          WAIT_MINUTES: ${{ github.event.inputs.wait_minutes }}
          CHILD_RUNS: ${{ github.event.inputs.child_runs }}
        run: |
          set -e # Dừng script nếu có lỗi

          WAIT_SECONDS=$(($WAIT_MINUTES * 60))
          NUM_TO_RESTART=$(($CHILD_RUNS / 2))
          if [ $NUM_TO_RESTART -eq 0 ]; then
             NUM_TO_RESTART=1
          fi

          echo "Cấu hình vòng lặp điều khiển:"
          echo "URL 1 (chính): $TARGET_URL_1"
          if [ -n "$TARGET_URL_2" ]; then
            echo "URL 2 (phụ): $TARGET_URL_2"
          else
            echo "URL 2 không được cung cấp. Tất cả runs sẽ dùng URL 1."
          fi
          echo "Tổng số worker duy trì: $CHILD_RUNS"
          echo "Số worker thay thế mỗi vòng: $NUM_TO_RESTART"
          echo "Thời gian chờ mỗi vòng: $WAIT_MINUTES phút ($WAIT_SECONDS giây)"
          echo "-----------------------------------------------------"

          echo "🚀 Bắt đầu khởi chạy 100% ($CHILD_RUNS) runs ban đầu..."
          for i in $(seq 1 $CHILD_RUNS); do
            CURRENT_URL="$TARGET_URL_1"
            if [ -n "$TARGET_URL_2" ] && (( i % 2 == 0 )); then
              CURRENT_URL="$TARGET_URL_2"
            fi
            echo "-> Kích hoạt lần chạy ban đầu $i với URL: $CURRENT_URL"
            gh workflow run Slow.yml --ref ${{ github.ref }} -f target_url="$CURRENT_URL"
          done

          sleep 20 # Chờ API của GitHub cập nhật

          echo "🔍 Lấy ID của các runs ban đầu và lưu lại..."
          # SỬA LỖI 1: Đổi '...' thành "..." và escape các dấu " bên trong
          ACTIVE_RUN_IDS=$(gh run list --workflow=Slow.yml --json databaseId,status,createdAt --limit $(($CHILD_RUNS + 5)) \
            --jq "[.[] | select(.status==\"queued\" or .status==\"in_progress\")] | sort_by(.createdAt) | reverse | .[0:$CHILD_RUNS] | .[].databaseId" | tr '\n' ' ')
          
          if [ -z "$ACTIVE_RUN_IDS" ]; then
              echo "❌ Không thể lấy ID các run ban đầu. Dừng workflow."
              exit 1
          fi
          echo "✅ Các run đang hoạt động: $ACTIVE_RUN_IDS"


          while true; do
            echo "-----------------------------------------------------"
            echo "⏳ Vòng lặp chính bắt đầu. Chờ $WAIT_MINUTES phút..."
            sleep $WAIT_SECONDS

            echo "🛑 Chuẩn bị dừng $NUM_TO_RESTART runs cũ nhất..."
            IDS_TO_STOP=$(echo "$ACTIVE_RUN_IDS" | cut -d' ' -f1-$NUM_TO_RESTART)
            IDS_TO_KEEP=$(echo "$ACTIVE_RUN_IDS" | cut -d' ' -f$(($NUM_TO_RESTART + 1))-)

            echo "-> Các ID sẽ bị dừng: $IDS_TO_STOP"
            for id in $IDS_TO_STOP; do
              echo "   -> Đang gửi lệnh hủy cho run ID: $id"
              gh run cancel $id || echo "   Lỗi khi hủy run ID $id (có thể nó đã kết thúc)."
            done
            echo "✅ Đã gửi lệnh hủy."

            echo "🧹 Dọn dẹp tất cả các runs đã dừng trong repository..."
            # SỬA LỖI 2: Đổi '...' thành "..." và escape các dấu " bên trong
            DELETABLE_RUN_IDS=$(gh run list --limit 100 --json databaseId,status \
              --jq "[.[] | select(.status==\"completed\" or .status==\"cancelled\" or .status==\"failure\")] | .[].databaseId" | tr '\n' ' ')
            if [ -n "$DELETABLE_RUN_IDS" ]; then
              for id in $DELETABLE_RUN_IDS; do
                (yes 2>/dev/null) | gh run delete $id >/dev/null 2>&1 || echo "Lỗi khi xóa run ID $id."
              done
              echo "✅ Đã dọn dẹp xong."
            else
              echo "👍 Không có run nào cần dọn dẹp."
            fi

            echo "🚀 Khởi chạy $NUM_TO_RESTART runs mới để thay thế..."
            for i in $(seq 1 $NUM_TO_RESTART); do
              CURRENT_URL="$TARGET_URL_1"
              if [ -n "$TARGET_URL_2" ] && (( i % 2 != 0 )); then
                CURRENT_URL="$TARGET_URL_2"
              fi
              echo "-> Kích hoạt lần chạy mới $i với URL: $CURRENT_URL"
              gh workflow run Slow.yml --ref ${{ github.ref }} -f target_url="$CURRENT_URL"
            done

            sleep 20 # Chờ API cập nhật

            echo "🔍 Lấy ID của $NUM_TO_RESTART runs mới..."
            # SỬA LỖI 3: Đổi '...' thành "..." và escape các dấu " bên trong
            NEW_RUN_IDS=$(gh run list --workflow=Slow.yml --json databaseId,status,createdAt --limit $(($NUM_TO_RESTART + 5)) \
              --jq "[.[] | select(.status==\"queued\" or .status==\"in_progress\")] | sort_by(.createdAt) | reverse | .[0:$NUM_TO_RESTART] | .[].databaseId" | tr '\n' ' ')

            if [ -z "$NEW_RUN_IDS" ]; then
                echo "⚠️ Không tìm thấy ID của các lần chạy mới. Sẽ giữ nguyên danh sách cũ và thử lại ở vòng lặp sau."
                ACTIVE_RUN_IDS="$IDS_TO_KEEP"
            else
                ACTIVE_RUN_IDS=$(echo "$IDS_TO_KEEP $NEW_RUN_IDS" | xargs)
                echo "✅ Đã lấy được các ID mới: $NEW_RUN_IDS"
            fi
            
            echo "🔄 Danh sách run hoạt động đã được cập nhật. Tổng số: $(echo $ACTIVE_RUN_IDS | wc -w)"
            echo "   Danh sách ID hiện tại: $ACTIVE_RUN_IDS"
            echo "   Chuẩn bị cho vòng lặp tiếp theo..."
          done
