
# 🅾️ File: .github/workflows/Slow.yml
name: 🚀 Auto Slow Cert:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL để chạy k6 test'
        required: true
        default: 'https://certapple.com'
jobs:
  k6_load_test:
    name: Chạy Test Cert
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Chạy k6 local test
        uses: k6io/k6-action@v0.3.1
        with:
          filename: Slow 
        env:
          TARGET_URL: ${{ github.event.inputs.target_url }}
