# ✅✅✅✅✅ controller.yml (Đã sửa lỗi quyền)
name: Controller - Run v4 in Loop
on:
  workflow_dispatch:
    inputs:
      target_url_1:
        description: 'URL Mục Tiêu 1 (bắt buộc)'
        required: true
        default: 'https://certapple.com'
      target_url_2:
        description: 'URL Mục Tiêu 2 (tùy chọn)'
        required: false
        default: 'https://signiosapp.com'
      loop_wait_minutes:
        description: 'Số Phút Chờ Mỗi Vòng Lặp'
        required: true
        default: '15'
      runs_per_loop:
        description: 'Số Lần Chạy Con (v4.yml) Mỗi Vòng Lặp'
        required: true
        default: '2'
      max_vus_per_job:
        description: 'Số Người Dùng Ảo Tối Đa (VUs) Mỗi Job'
        required: true
        default: '500'
      child_run_duration:
        description: 'Thời gian chạy của mỗi job con (phút)'
        required: true
        default: '10'

jobs:
  loop-controller:
    runs-on: ubuntu-latest
    
    # === FIX: THÊM KHỐI PERMISSIONS ===
    # Cấp quyền cho GITHUB_TOKEN để có thể kích hoạt workflow khác.
    permissions:
      actions: write   # Bắt buộc để chạy `gh workflow run`
      contents: read   # Tốt nhất nên có để `actions/checkout` hoạt động ổn định

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Vòng lặp vô hạn để kích hoạt v4.yml
        env:
          # GITHUB_TOKEN sẽ tự động nhận quyền từ khối permissions ở trên
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_URL_1: ${{ github.event.inputs.target_url_1 }}
          TARGET_URL_2: ${{ github.event.inputs.target_url_2 }}
          RUNS_PER_LOOP: ${{ github.event.inputs.runs_per_loop }}
          MAX_VUS: ${{ github.event.inputs.max_vus_per_job }}
          CHILD_DURATION: ${{ github.event.inputs.child_run_duration }}
          WAIT_MINUTES: ${{ github.event.inputs.loop_wait_minutes }}
        run: |
          # Vòng lặp này sẽ chạy mãi mãi cho đến khi bạn hủy thủ công
          while true; do
            echo "--- BẮT ĐẦU VÒNG LẶP MỚI ---"
            echo "Sẽ kích hoạt v4.yml ${RUNS_PER_LOOP} lần."

            # Vòng lặp for để chạy v4.yml theo số lần đã định
            for i in $(seq 1 $RUNS_PER_LOOP)
            do
              echo ">> Bắt đầu lần chạy con thứ $i/${RUNS_PER_LOOP}..."
              gh workflow run v4.yml \
                --ref ${{ github.ref_name }} \
                -f target_url_1="$TARGET_URL_1" \
                -f target_url_2="$TARGET_URL_2" \
                -f k6_max_vus="$MAX_VUS" \
                -f k6_duration="$CHILD_DURATION"

              # Chờ một chút giữa các lần kích hoạt để tránh spam API của GitHub
              echo ">> Đã kích hoạt. Chờ 5 giây trước khi tiếp tục..."
              sleep 5
            done

            echo "--- KẾT THÚC CÁC LẦN KÍCH HOẠT ---"
            echo "Đang chờ ${WAIT_MINUTES} phút trước khi bắt đầu vòng lặp tiếp theo..."

            # Chuyển phút sang giây để lệnh sleep hoạt động
            sleep $((WAIT_MINUTES * 60))
          done
